### ISSUE TITLE
Bad alloc!

### ISSUE THREAD

**Issue by zvezdochiot** [ZQPei/patchmatch_inpainting#1]
https://github.com/ZQPei/patchmatch_inpainting/blob/0bea9c6c62f1347841fd903d45bebbe2d8e2388e/source/main.cpp#L63-L65

Maybe?:
```cpp
	int ** mask = (int **)calloc(int(height), sizeof(int*));
	for (int i = 0; i < height; i++)
            mask[i] = (int *)calloc(int(width), sizeof(int));
```
See:
https://github.com/ZQPei/patchmatch_inpainting/blob/0bea9c6c62f1347841fd903d45bebbe2d8e2388e/source/main.cpp#L127-L130

**Comment by ZQPei** [comment]
I think you are probably right. The images I use are square, so I did not see this bug.

**Comment by zvezdochiot** [comment]
Testing https://github.com/ZQPei/patchmatch_inpainting/tree/master/image_files/forest

**Comment by zvezdochiot** [comment]
Fixed. :)
