### ISSUE TITLE
Version for maintainer?

### ISSUE THREAD

**Issue by zvezdochiot** [ZQPei/patchmatch_inpainting#8]
Maybe add to https://github.com/ZQPei/patchmatch_inpainting/releases : 

0.1 "simpe version"
* fix #1: bad alloc
* fix #2: name tools
* fix #3: simple tools
* fix #4: change LICENSE
* fix #5: g++ version

**Comment by zvezdochiot** [comment]
https://github.com/ZQPei/patchmatch_inpainting/releases/tag/0.1

**Comment by ZQPei** [comment]
Sure, good idea.
